sudo: false

language: go

os:
 - linux
 - osx

go:
- 1.6
- tip

script:
  echo $TRAVIS_GO_VERSION
  ./test.sh
  mkdir ${TRAVIS_OS_NAME}
  ln piknik ${TRAVIS_OS_NAME}/
  tar czpvf piknik-${TRAVIS_OS_NAME}_$(arch)-${TRAVIS_TAG}.tar.gz ${TRAVIS_OS_NAME}

deploy:
  provider: releases
  api_key:
    secure: jtXaCwUY+LlovLJQgT+V2lDYvW/dHRWHZGiZLReJP19GA1x0aAFTzRBeESbvJ92lYu5HGOL6nmFUKn8Fl+HQ8kocK2bTE16AnvBxtLIgmOElHA2W+dIiJnIl7EfG9kNxzV75eGcH/YN+Skqwq95XmTsn9TvFhIPTcY1WuoV239fqS+rcDg3zdr0uM/kcYbyO7OFkvKU4ewTx5QoDJVgLDQo2fnPtGVsPr0M8XSFpTlfpmpJzEOS30aEOE18qKZaz/suNDO4Zgya7O374xQbY6WTiChpUMTTwQRuiExj3/8soSRPWXazZrHdkX+2My6gaZEslVRdCa4CUP6tPJoIX4b5Dmi3+WkYRkeUNNqpP+m26nV9PapQqg7S5K5lXjfaCkGGZLg/wLhtjeuGdk6H1+bbyPprxdXhplBV7yzDyjNWcbFFruOcvsuks9zBYIelR9dlFiIb33gq/zsams7usZNERvisR3bBLecH9qdxcimp/DB+tEN4i8aNGz+dYmHvWBAxNw+GjGiSs6wnZrJtqex1Q2j5ngSLDgMDiSHamd0m/yQjnN5jKklIIEgIhaS+jp50Qi3mMmnv03KvLbulmLkfh/vQ612F+gH/N+UbtDeva5SPGH4I/X01gJoHGGbXVmqlv2F1cwkFnWbY50kGIaHOLQFsWxUzjyBXPVXItRxQ=
  file: piknik-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: jedisct1/piknik
    tags: true
    condition: "${TRAVIS_GO_VERSION}" == "1.6"

after_deploy:
  - ls -l piknik-*.tar.gz
